### ISSUE TITLE
AntiLag is also non-violent

### ISSUE THREAD

**Issue by Nyastra** [bizzlemip2/webfishing-antilag#1]
Not sure if it's intended, but given that there's no mention of it, I assume it's not?
The mod prevents you from punching other players, though they can still punch you

**Comment by Nyastra** [comment]
Apologies, I may have been too hasty, it seems like it must be coming from something else? Hard for me to say for certain, but there's a strong likelihood that it was just a coincidence that disabling your mod fixed it for a friend, whereas I had to disable AntiLag and Xenon both.

**Comment by bizzlemip2** [comment]
Noted! Very well might be a bug with the mod. Will have to verify though
